language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pytest -sv --cov=algos --cov=algoscli tests
after_success:
  - coveralls
